# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'film_lib_add_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.labelTitle = QtWidgets.QLabel(Dialog)
        self.labelTitle.setObjectName("labelTitle")
        self.gridLayout.addWidget(self.labelTitle, 0, 0, 1, 1)
        self.lineEditTitle = QtWidgets.QLineEdit(Dialog)
        self.lineEditTitle.setObjectName("lineEditTitle")
        self.gridLayout.addWidget(self.lineEditTitle, 0, 1, 1, 1)
        self.comboBoxGenre = QtWidgets.QComboBox(Dialog)
        self.comboBoxGenre.setObjectName("comboBoxGenre")
        self.gridLayout.addWidget(self.comboBoxGenre, 2, 1, 1, 1)
        self.labelYear = QtWidgets.QLabel(Dialog)
        self.labelYear.setObjectName("labelYear")
        self.gridLayout.addWidget(self.labelYear, 1, 0, 1, 1)
        self.lineEditYear = QtWidgets.QLineEdit(Dialog)
        self.lineEditYear.setObjectName("lineEditYear")
        self.gridLayout.addWidget(self.lineEditYear, 1, 1, 1, 1)
        self.labelGenre = QtWidgets.QLabel(Dialog)
        self.labelGenre.setObjectName("labelGenre")
        self.gridLayout.addWidget(self.labelGenre, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.lineEditDuration = QtWidgets.QLineEdit(Dialog)
        self.lineEditDuration.setObjectName("lineEditDuration")
        self.gridLayout.addWidget(self.lineEditDuration, 3, 1, 1, 1)
        self.btnAdd = QtWidgets.QPushButton(Dialog)
        self.btnAdd.setObjectName("btnAdd")
        self.gridLayout.addWidget(self.btnAdd, 4, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Добавить элемент"))
        self.labelTitle.setText(_translate("Dialog", "Называние"))
        self.labelYear.setText(_translate("Dialog", "Год выпуска"))
        self.labelGenre.setText(_translate("Dialog", "Жанр"))
        self.label_4.setText(_translate("Dialog", "Длина"))
        self.btnAdd.setText(_translate("Dialog", "Добавить"))
