# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pil2.0.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.btnAll = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.btnAll.sizePolicy().hasHeightForWidth())
        self.btnAll.setSizePolicy(sizePolicy)
        self.btnAll.setObjectName("btnAll")
        self.gridLayout.addWidget(self.btnAll, 3, 0, 1, 1)
        self.btnB = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.btnB.sizePolicy().hasHeightForWidth())
        self.btnB.setSizePolicy(sizePolicy)
        self.btnB.setObjectName("btnB")
        self.gridLayout.addWidget(self.btnB, 2, 0, 1, 1)
        self.btnG = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.btnG.sizePolicy().hasHeightForWidth())
        self.btnG.setSizePolicy(sizePolicy)
        self.btnG.setObjectName("btnG")
        self.gridLayout.addWidget(self.btnG, 1, 0, 1, 1)
        self.btnR = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.btnR.sizePolicy().hasHeightForWidth())
        self.btnR.setSizePolicy(sizePolicy)
        self.btnR.setObjectName("btnR")
        self.gridLayout.addWidget(self.btnR, 0, 0, 1, 1)
        self.image = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image.sizePolicy().hasHeightForWidth())
        self.image.setSizePolicy(sizePolicy)
        self.image.setObjectName("image")
        self.gridLayout.addWidget(self.image, 0, 1, 4, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnCouterclockwise = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.btnCouterclockwise.sizePolicy().hasHeightForWidth())
        self.btnCouterclockwise.setSizePolicy(sizePolicy)
        self.btnCouterclockwise.setObjectName("btnCouterclockwise")
        self.horizontalLayout.addWidget(self.btnCouterclockwise)
        self.btnClockwise = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.btnClockwise.sizePolicy().hasHeightForWidth())
        self.btnClockwise.setSizePolicy(sizePolicy)
        self.btnClockwise.setObjectName("btnClockwise")
        self.horizontalLayout.addWidget(self.btnClockwise)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PIL 2.0"))
        self.btnAll.setText(_translate("MainWindow", "ALL"))
        self.btnB.setText(_translate("MainWindow", "B"))
        self.btnG.setText(_translate("MainWindow", "G"))
        self.btnR.setText(_translate("MainWindow", "R"))
        self.image.setText(_translate("MainWindow", "TextLabel"))
        self.btnCouterclockwise.setText(_translate("MainWindow", "Против часовой стрелке"))
        self.btnClockwise.setText(_translate("MainWindow", "По часовой стрелке"))
