# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'random_flag_gen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnColorNumber = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnColorNumber.sizePolicy().hasHeightForWidth())
        self.btnColorNumber.setSizePolicy(sizePolicy)
        self.btnColorNumber.setIconSize(QtCore.QSize(20, 20))
        self.btnColorNumber.setAutoDefault(False)
        self.btnColorNumber.setObjectName("btnColorNumber")
        self.verticalLayout.addWidget(self.btnColorNumber)
        self.drawCanvas = QtWidgets.QWidget(self.centralwidget)
        self.drawCanvas.setObjectName("drawCanvas")
        self.verticalLayout.addWidget(self.drawCanvas)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Генерация флага"))
        self.btnColorNumber.setText(_translate("MainWindow", "Ввести количество цветов флага"))
