import sys
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cbCheesburger = QtWidgets.QCheckBox(self.centralwidget)
        self.cbCheesburger.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbCheesburger.sizePolicy().hasHeightForWidth())
        self.cbCheesburger.setSizePolicy(sizePolicy)
        self.cbCheesburger.setObjectName("cbCheesburger")
        self.horizontalLayout.addWidget(self.cbCheesburger)
        self.spinBoxCheesburger = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxCheesburger.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(23)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxCheesburger.sizePolicy().hasHeightForWidth())
        self.spinBoxCheesburger.setSizePolicy(sizePolicy)
        self.spinBoxCheesburger.setObjectName("spinBoxCheesburger")
        self.horizontalLayout.addWidget(self.spinBoxCheesburger)
        spacerItem = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cbGamburger = QtWidgets.QCheckBox(self.centralwidget)
        self.cbGamburger.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbGamburger.sizePolicy().hasHeightForWidth())
        self.cbGamburger.setSizePolicy(sizePolicy)
        self.cbGamburger.setObjectName("cbGamburger")
        self.horizontalLayout_2.addWidget(self.cbGamburger)
        self.spinBoxGamburger = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxGamburger.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(23)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxGamburger.sizePolicy().hasHeightForWidth())
        self.spinBoxGamburger.setSizePolicy(sizePolicy)
        self.spinBoxGamburger.setObjectName("spinBoxGamburger")
        self.horizontalLayout_2.addWidget(self.spinBoxGamburger)
        spacerItem1 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cbCocaCola = QtWidgets.QCheckBox(self.centralwidget)
        self.cbCocaCola.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbCocaCola.sizePolicy().hasHeightForWidth())
        self.cbCocaCola.setSizePolicy(sizePolicy)
        self.cbCocaCola.setObjectName("cbCocaCola")
        self.horizontalLayout_3.addWidget(self.cbCocaCola)
        self.spinBoxCocaCola = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxCocaCola.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(23)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxCocaCola.sizePolicy().hasHeightForWidth())
        self.spinBoxCocaCola.setSizePolicy(sizePolicy)
        self.spinBoxCocaCola.setObjectName("spinBoxCocaCola")
        self.horizontalLayout_3.addWidget(self.spinBoxCocaCola)
        spacerItem2 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cbNugget = QtWidgets.QCheckBox(self.centralwidget)
        self.cbNugget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbNugget.sizePolicy().hasHeightForWidth())
        self.cbNugget.setSizePolicy(sizePolicy)
        self.cbNugget.setObjectName("cbNugget")
        self.horizontalLayout_4.addWidget(self.cbNugget)
        self.spinBoxNugget = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxNugget.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(23)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxNugget.sizePolicy().hasHeightForWidth())
        self.spinBoxNugget.setSizePolicy(sizePolicy)
        self.spinBoxNugget.setObjectName("spinBoxNugget")
        self.horizontalLayout_4.addWidget(self.spinBoxNugget)
        spacerItem3 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem4 = QtWidgets.QSpacerItem(200, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem4)
        self.btnOrder = QtWidgets.QPushButton(self.centralwidget)
        self.btnOrder.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOrder.sizePolicy().hasHeightForWidth())
        self.btnOrder.setSizePolicy(sizePolicy)
        self.btnOrder.setObjectName("btnOrder")
        self.verticalLayout.addWidget(self.btnOrder)
        spacerItem5 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem5)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit.sizePolicy().hasHeightForWidth())
        self.plainTextEdit.setSizePolicy(sizePolicy)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.plainTextEdit)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Заказ в Макдональдсе — 2"))
        self.cbCheesburger.setText(_translate("MainWindow", "Чизбургер"))
        self.cbGamburger.setText(_translate("MainWindow", "Гамбургер"))
        self.cbCocaCola.setText(_translate("MainWindow", "Кока-кола"))
        self.cbNugget.setText(_translate("MainWindow", "Нагетсы"))
        self.btnOrder.setText(_translate("MainWindow", "Заказать"))


class MainWindow(QtWidgets.QMainWindow, Ui_MainWindow):

    def __init__(self):
        super(MainWindow, self).__init__()
        self.setupUi(self)
        self.prices = {'Чизбургер': 80, 'Гамбургер': 60, 'Кока-кола': 100, 'Нагетсы': 130}

    def setupUi(self, MainWindow):
        super().setupUi(MainWindow)
        for cb in (getattr(self, i) for i in self.__dict__ if i.startswith('cb')):
            cb.toggled.connect(self.add_order)
        self.btnOrder.clicked.connect(self.create_order)

    def add_order(self):
        name = self.sender().objectName()
        spin: QtWidgets.QSpinBox = getattr(self, f'spinBox{name.removeprefix("cb")}')
        if self.sender().isChecked():
            spin.setDisabled(False)
            spin.setMinimum(1)
            spin.setValue(1)
        else:
            spin.setDisabled(True)
            spin.setMinimum(0)
            spin.setValue(0)

    def create_order(self):
        self.plainTextEdit.setPlainText('Ваш заказ:\n')
        res = 0
        for cb in (getattr(self, i) for i in self.__dict__ if i.startswith('cb')):
            if cb.isChecked():
                spin = getattr(self, f'spinBox{cb.objectName().removeprefix("cb")}')
                number = spin.value()
                name = cb.text()
                price = self.prices[name]
                price = price * number
                res += price
                order = name.ljust(20) + str(number)
                order = order.ljust(40) + str(price)
                self.plainTextEdit.appendPlainText(order)
        self.plainTextEdit.appendPlainText(f'\nИтого: {res}')
        if res == 0:
            self.plainTextEdit.clear()


def main():
    app = QtWidgets.QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec())


if __name__ == '__main__':
    main()
