# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'planning.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(950, 660)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setObjectName("calendarWidget")
        self.gridLayout.addWidget(self.calendarWidget, 1, 1, 1, 1)
        self.lineEditEvent = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditEvent.setObjectName("lineEditEvent")
        self.gridLayout.addWidget(self.lineEditEvent, 2, 1, 1, 1)
        self.btnAddEvent = QtWidgets.QPushButton(self.centralwidget)
        self.btnAddEvent.setObjectName("btnAddEvent")
        self.gridLayout.addWidget(self.btnAddEvent, 3, 1, 1, 1)
        self.timeEdit = QtWidgets.QTimeEdit(self.centralwidget)
        self.timeEdit.setObjectName("timeEdit")
        self.gridLayout.addWidget(self.timeEdit, 0, 1, 1, 1)
        self.listEvents = QtWidgets.QListWidget(self.centralwidget)
        self.listEvents.setObjectName("listEvents")
        self.gridLayout.addWidget(self.listEvents, 0, 2, 4, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Минипланировщик"))
        self.btnAddEvent.setText(_translate("MainWindow", "Добавить событие"))
